### ISSUE TITLE
--schema argument doesn't seem to be considered when scaffolding db

### ISSUE THREAD

**Issue by Rotbarsch** [ErikEJ/EFCorePowerTools#1262]
Hello again, thanks for your quick help with yesterdays issue. Today, I have the following problem:

I'm having multiple schemas in my .dacpac file, but I only need to scaffold for one of them. I try to use the --schema argument; but sadly it generates entities and DbContext for every schema in the dacpac file. So for example: I have the schemas "mat" and "mat2" defined in my dacpac and supply the "--schema mat" argument - but I still get the entities of "mat2", too.

I even tried the workaround "--schema nonexistantSchema --schema mat" you mention in the readme, but alas to no avail. 

### Steps to reproduce

I prepared a minimal reproduction for your use: https://github.com/Rotbarsch/ErikEJDacPacRepro
Run the generate.ps1 to produce entities for schemas "mat" and "mat2", even if the argument "--schema mat" is supplied.

### Further technical details

EF Core version in use: EF Core 6

EF Core Power Tools version: 6.0.1-preview2

Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
Please share your exact command line

**Comment by Rotbarsch** [comment]
dotnet ef dbcontext scaffold `
"$dacpacFile" ErikEJ.EntityFrameworkCore.SqlServer.Dacpac `
--context MATDBContext `
-o Entities `
--schema mat `
--context-dir . `
--data-annotations `
--schema mat `
--force

**Comment by ErikEJ** [comment]
Try to be explict about the tables

**Comment by Rotbarsch** [comment]
I changed my command line call to the following:

dotnet ef dbcontext scaffold `
"$dacpacFile" ErikEJ.EntityFrameworkCore.SqlServer.Dacpac `
--context MATDBContext `
-o Entities `
--schema mat `
--context-dir . `
--data-annotations `
--table "[mat2].[language]"`
--force

It still produces every entity in the dacpac.

**Comment by ErikEJ** [comment]
Remove the double quotes ?

**Comment by Rotbarsch** [comment]
No changes. 

I had a quick glimpse at your SqlServerDacpacDatabaseModelFactory; it seems like your Library scaffolds all entities regardless of supplied parameters.

**Comment by ErikEJ** [comment]
Indeed! https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/Scaffolding/SqlServerDacpacDatabaseModelFactory.cs#L75

**Comment by Rotbarsch** [comment]
Do you plan on releasing another preview release with a fix?

**Comment by ErikEJ** [comment]
I think there were some issues with this in relation to usage from EF Core Power Tools  but it is obviously something that should be fixed...

**Comment by ErikEJ** [comment]
The only reason for preview label is due to DacFX for .NET 6 not release yet

**Comment by ErikEJ** [comment]
Ah!  It was just a bug: https://github.com/ErikEJ/EFCorePowerTools/blame/85bfa10a448d408d76fadd9c1029002176315a7d/src/GUI/ErikEJ.EntityFrameworkCore.SqlServer.Dacpac/Scaffolding/SqlServerDacpacDatabaseModelFactory.cs#L75 - I will fix soonest

**Comment by ErikEJ** [comment]
Updated NuGet package published, thanks for reporting this

**Comment by Rotbarsch** [comment]
I can confirm the usage of --table works now with 6.0.1-preview3, but sadly --schema still shows the same behavior.

**Comment by ErikEJ** [comment]
I think that has never worked, the workaround concerns the default schema, not filtering

**Comment by Rotbarsch** [comment]
I think I found a way to implement this functionality. Please see the supplied pull request:

https://github.com/ErikEJ/EFCorePowerTools/pull/1263

**Comment by ErikEJ** [comment]
Thanks for your contribution, Nuget package 6.0.1 just published (DacFX 160 was just released!)
