### ISSUE TITLE
Customize CodeTemplates folder location

### ISSUE THREAD

**Issue by ClaudioBiagioli** [ErikEJ/EFCorePowerTools#1868]
We are going to create a solution with many projects. 
Each project will have his own DBContext. 
We'll use Reverse Engineering to create the DBContexts from the different Databases and Code customization using T4 templates.

Now, I would like to use a single set of T4 files, either to reduce code and to reduce the work for the development team.
At the moment the CodeTemplates folder is created (and I think searched) in the project folder.

I was wondering if it is possible to add a configuration key in order to customize the location or also the name of the folder with a relative or absolute path.

Thanks

### Provide technical details

- EF Core version in use: EF Core 7)

- Is Handlebars used: yes

- Is T4 used: yes

- Is .dacpac used: no

- EF Core Power Tools version: 2.5.1429

- Database engine: SQL Server

- Visual Studio version: Visual Studio 2022

**Comment by ErikEJ** [comment]
The folder structure is hardcoded (CodeTemplates/EFCore), but the path is settable, but right now just points to the project path. Adding an override to a full or even relative path would indeed be possible.

**Comment by ErikEJ** [comment]
Interested in doing a PR?

**Comment by ClaudioBiagioli** [comment]
Well, the mine was more a request for a new feature 😝 
But since you've suggested that, I can try and check the code in my spare time: it shouldn't be a complex change.
I'll let you know. 😉

**Comment by ErikEJ** [comment]
@ClaudioBiagioli You could sponsor me and I can implement it for you!

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by ErikEJ** [comment]
@ClaudioBiagioli I have been thinking about this, and it sounds like a good general feature. I will look into it.

**Comment by ErikEJ** [comment]
I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by ClaudioBiagioli** [comment]
Hi @ErikEJ , I installed the latest build (2.5.1538). 
I set in the **efpt.config.json** the value:
_"T4TemplatePath": "..\\..\\CodeTemplates",_
but the CodeTemplates is still created/read in the project folder.

Am I doing something wrong?

**Comment by ErikEJ** [comment]
@ClaudioBiagioli Most likely not, seems it need to fix the part where I drop/install the templates also

**Comment by ErikEJ** [comment]
@ClaudioBiagioli You should use:

```json
"T4TemplatePath": "..\\..\\CodeTemplates",
```

**Comment by ClaudioBiagioli** [comment]
Tried full path with and without CodeTemplates, still doesn't work.

**Comment by ErikEJ** [comment]
How do you verify "not working" ?

**Comment by ErikEJ** [comment]
I will do some testing tomorrow

**Comment by ClaudioBiagioli** [comment]
Well, I expect the the CodeTemplates folder, if not existing, is created in/read from the FolderPath specified in the config.
Instead,  even if I delete the folder, it's always recreated in the project root folder.

**Comment by ErikEJ** [comment]
I found the bug, a missing mapping. 

And yes, the folder unpacking is another issue, but not a showstopper.

I have this, and it works after my bug fix:

```json
  "UseT4": true,
  "T4TemplatePath": "C:\\temp"
```

I implemented a fix for this in the [latest daily build](https://www.vsixgallery.com/extension/f4c4712c-ceae-4803-8e52-0e2049d5de9f), would be grateful if you could try it out.

**Comment by ErikEJ** [comment]
You need build .1539 or later.

I have also created https://github.com/ErikEJ/EFCorePowerTools/issues/1875
