### ISSUE TITLE
No EF Core DbContext types found in the project

### ISSUE THREAD

**Issue by tonysneed** [ErikEJ/EFCorePowerTools#56]
When I attempted to add a DbContext model diagram, I received the following error:
```
System.ArgumentException: No EF Core DbContext types found in the project
   at ReverseEngineer20.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 76
   at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 34
   at ReverseEngineer20.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt\Program.cs:line 44

Parameter name: processResult
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 49
```

The same error occurred when executing any of the other DbContext related commands in EF Core Power Tools, even though a DbContext does indeed exist in the project.

### Further technical details
EF Core Power Tools version: 1.0.617

Database engine: SQL Server

Visual Studio version: Visual Studio 2017 15.7.4

**Comment by ErikEJ** [comment]
Pls share your DbContext

**Comment by tonysneed** [comment]
You bet ... The class was produced with the EFC PT by reverse engineering a database I use called NorthwindSlim.

```csharp
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ClassLibrary1
{
    public partial class NorthwindslimContext : DbContext
    {
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<CustomerSetting> CustomerSetting { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeeTerritories> EmployeeTerritories { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderDetail> OrderDetail { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Territory> Territory { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Data Source='(localdb)\\MsSqlLocalDb';Integrated Security=True;Pooling=False;Initial Catalog='NorthwindSlim'");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Category>(entity =>
            {
                entity.Property(e => e.CategoryName)
                    .IsRequired()
                    .HasMaxLength(15);
            });

            modelBuilder.Entity<Customer>(entity =>
            {
                entity.Property(e => e.CustomerId)
                    .HasMaxLength(5)
                    .ValueGeneratedNever();

                entity.Property(e => e.City).HasMaxLength(15);

                entity.Property(e => e.CompanyName)
                    .IsRequired()
                    .HasMaxLength(40);

                entity.Property(e => e.ContactName).HasMaxLength(30);

                entity.Property(e => e.Country).HasMaxLength(15);
            });

            modelBuilder.Entity<CustomerSetting>(entity =>
            {
                entity.HasKey(e => e.CustomerId);

                entity.Property(e => e.CustomerId)
                    .HasMaxLength(5)
                    .ValueGeneratedNever();

                entity.Property(e => e.Setting)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.HasOne(d => d.Customer)
                    .WithOne(p => p.CustomerSetting)
                    .HasForeignKey<CustomerSetting>(d => d.CustomerId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_CustomerSetting_Customer");
            });

            modelBuilder.Entity<Employee>(entity =>
            {
                entity.Property(e => e.BirthDate).HasColumnType("datetime");

                entity.Property(e => e.City).HasMaxLength(15);

                entity.Property(e => e.Country).HasMaxLength(15);

                entity.Property(e => e.FirstName)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.Property(e => e.HireDate).HasColumnType("datetime");

                entity.Property(e => e.LastName)
                    .IsRequired()
                    .HasMaxLength(20);
            });

            modelBuilder.Entity<EmployeeTerritories>(entity =>
            {
                entity.HasKey(e => new { e.EmployeeId, e.TerritoryId });

                entity.Property(e => e.TerritoryId).HasMaxLength(20);

                entity.HasOne(d => d.Employee)
                    .WithMany(p => p.EmployeeTerritories)
                    .HasForeignKey(d => d.EmployeeId)
                    .HasConstraintName("FK_dbo.EmployeeTerritories_dbo.Employee_EmployeeId");

                entity.HasOne(d => d.Territory)
                    .WithMany(p => p.EmployeeTerritories)
                    .HasForeignKey(d => d.TerritoryId)
                    .HasConstraintName("FK_dbo.EmployeeTerritories_dbo.Territory_TerritoryId");
            });

            modelBuilder.Entity<Order>(entity =>
            {
                entity.Property(e => e.CustomerId).HasMaxLength(5);

                entity.Property(e => e.Freight)
                    .HasColumnType("money")
                    .HasDefaultValueSql("((0))");

                entity.Property(e => e.OrderDate).HasColumnType("datetime");

                entity.Property(e => e.ShippedDate).HasColumnType("datetime");

                entity.HasOne(d => d.Customer)
                    .WithMany(p => p.Order)
                    .HasForeignKey(d => d.CustomerId)
                    .HasConstraintName("FK_Orders_Customers");
            });

            modelBuilder.Entity<OrderDetail>(entity =>
            {
                entity.Property(e => e.Quantity).HasDefaultValueSql("((1))");

                entity.Property(e => e.UnitPrice).HasColumnType("money");

                entity.HasOne(d => d.Order)
                    .WithMany(p => p.OrderDetail)
                    .HasForeignKey(d => d.OrderId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Order_Details_Orders");

                entity.HasOne(d => d.Product)
                    .WithMany(p => p.OrderDetail)
                    .HasForeignKey(d => d.ProductId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Order_Details_Products");
            });

            modelBuilder.Entity<Product>(entity =>
            {
                entity.Property(e => e.ProductName)
                    .IsRequired()
                    .HasMaxLength(40);

                entity.Property(e => e.RowVersion).IsRowVersion();

                entity.Property(e => e.UnitPrice)
                    .HasColumnType("money")
                    .HasDefaultValueSql("((0))");

                entity.HasOne(d => d.Category)
                    .WithMany(p => p.Product)
                    .HasForeignKey(d => d.CategoryId)
                    .HasConstraintName("FK_Products_Categories");
            });

            modelBuilder.Entity<Territory>(entity =>
            {
                entity.Property(e => e.TerritoryId)
                    .HasMaxLength(20)
                    .ValueGeneratedNever();

                entity.Property(e => e.TerritoryDescription)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
```

**Comment by ErikEJ** [comment]
Yikes! Pls share a repro project, thanks!

**Comment by tonysneed** [comment]
Here you go: https://github.com/tonysneed/Demo.EFCorePowerTools.DbContextError

**Comment by ErikEJ** [comment]
It is because I do not support 2.1.1 (yet) !!! Change to 2.1.0 and it will work.

**Comment by ErikEJ** [comment]
Fixed in latest daily build

**Comment by tonysneed** [comment]
@ErikEJ Thanks!

**Comment by TC-SopraSteria** [comment]
Hi, facing the same issue within .Net core 2.2 Projects
Do you have an eta on a repackage ?
Thanks.

**Comment by light-traveller** [comment]
I have already installed .Net Core 2.2 runtime and SDK plus the latest version of EF Core Power Tools from VS Gallery. Moreover, I have set up my projects to use .Net Core 2.2; Still getting the following error when running the migration tool:

![image](https://user-images.githubusercontent.com/11184964/50574139-6ab76d80-0df7-11e9-86ad-4c454940afbe.png)

P.S. my `DbContext` inherits from `IdentityDbContext`

**Comment by ErikEJ** [comment]
@The-DevOps-Guy Latest daily build supports EF Core 2.2

**Comment by ErikEJ** [comment]
@light-traveller Latest daily build supports EF Core 2.2, but you could also be facing #15

**Comment by OvaisMemon** [comment]
Hi @ErikEJ 

I'm using .Net 8.0 SDK winforms application and using EFCore 8.0 for sqlite. When trying to add a migration on my class library project contains my DbContext, it is giving me the below error. Can you pls sort it out.

![image](https://github.com/ErikEJ/EFCorePowerTools/assets/22098509/243f42e3-896e-4528-89d1-31b9ef31da0c)


Thanks

**Comment by ErikEJ** [comment]
@OvaisMemon this issue is closed, and I have decided to remove the migrations tool  - please read the wiki for alternatives
